appointments/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^appointment/$',views.appointmentslot.as_view(), name="appointment"),
    url(r'^doctoravailability/$',views.DoctorSlotspost.as_view(), name="doctortimes"),
    url(r'^slots/(?P<doctor_id>[0-9]+)/$',views.getappoints, name="appointment"),
    url(r'^appointment/(?P<doctor_id>[0-9]+)/$',views.appointmentchoices.as_view(), name="choices"),
    url(r'^getappointment/(?P<patient_id>[A-Z]+-00-[0-9]+)/$',views.getappointtime.as_view(), name='getappointtime'),
    url(r'^consultfee/$',views.generatebill.as_view(), name='bill'),
    url(r'^consultation/(?P<id>[0-9]+)/$',views.Opdappointment.as_view()),
    url(r'^consultfee/get/(?P<patient_id>[A-Z]+-00-[0-9]+)/$',views.billget.as_view(), name='getbill'),
    url(r'^consultationfee/(?P<id>[0-9]+)/$',views.consultfeeview, name='getbill'),
    url(r'^multibreak/$', views.multibreakslots, name='getbill'),
    url(r'^blockslot/(?P<doctor_id>[0-9]+)/$',views.BlockslotView.as_view(), name="choices"),
]

bms/urls.py
from django.conf.urls import url
from . import views
#(?P<pk>[0-9]*)

urlpatterns = [
    url(r'^wards/(?P<pk>[0-9]*)$', views.WardView.as_view()),
    url(r'^floors/(?P<pk>[0-9]*)$',views.FloorView.as_view()),
    url(r'^rooms/(?P<pk>[0-9]*)$',views.RoomsView.as_view()),
    url(r'^roomsbeds/(?P<roomNo>[0-9]+)/$', views.RoomsRetriveView.as_view()),
    url(r'^roomsbeds/$',views.RoomsListView.as_view()),
    url(r'^roomtype/(?P<pk>[0-9]*)$', views.RoomstypeView.as_view()),
    url(r'^bed_details/(?P<roomNo>[0-9]*)$',views.Getbedsview.as_view()),
    url(r'^beds/(?P<pk>[0-9]*)$',views.BedTableView.as_view()),
    url(r'^bed/((?P<appointment_id>[0-9]*)/(?P<textflag>[a-zA-Z0-9]*))*/*$', views.AppointedBedView.as_view()),
    # url(r'^floors/$',views.createFloor.as_view()),
    # url(r'room/$',views.Createrooms.as_view()),
    # url(r'getbeds/(?P<roomNo>[0-9]*)$',views.Getbedsview.as_view()),
    url(r'^bms_list/$', views.bms_list_view, name='bedmanagement'),
    url(r'^rooms_list/$', views.rooms_list_view, name='roomsmanagement'),
    url(r'^bedstatus/(?P<appointmenId>[0-9]*)$', views.appointbedCreateApiview.as_view()),
    url(r'^bedappointed/(?P<appointmentid>[0-9]*)$', views.AppointedBedView.as_view()),
    url(r'^NurseInpatient_table/$', views.NurseInpatient_table_view, name='nurseinpatient'),
    url(r'^NurseInpatient_transfer/(?P<appointment>[0-9]*)$', views.NurseInpatient_transfer_view, name='nurseinpatient'),
]

cygenhms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.views.generic.base import TemplateView
from rest_framework.authtoken import views

from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^', include(('patientmanagement.urls','patientmanagement'), namespace='ehr')),
    # url(r'^', include(('hospitalcodes.urls','hospitalcode'), namespace='hospitalcodes')),
    url(r'^', include(('usermanagement.urls','usermanagement'), namespace='usemanagement')),
    url(r'^', include(('appointments.urls','appointments'), namespace='appointments')),
    url(r'^', include(('billing.urls','billing'), namespace='billing')),
    url(r'^', include(('bms.urls','bms'), namespace='bms')),
    url(r'^', include(('pharmacy.urls','pharmacy'), namespace='pharmacy')),
    url(r'^', include(('inventory.urls','inventory'), namespace='inventory')),
    # url(r'^', include('appointments.urls', namespace='appointmentcalender')),
    # url(r'^api-token-refresh/', refresh_jwt_token),
    # url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^hms/', csrf_exempt(TemplateView.as_view(template_name="index.html")), name="home"),
    url(r'^Hms/', csrf_exempt(TemplateView.as_view(template_name="index1.html")), name="home"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]

pharmacy/urls.py
from .views import *
from django.conf.urls import url


urlpatterns = [
    url(r'^api/customers/', customer_list),
    url(r'^api/customer/(?P<pk>[0-9]+)', customer_detail),
    url(r'^api/orders/', order_list),
    url(r'^api/order/(?P<pk>[0-9]+)', order_details),
    url(r'^api/purchasetax/', tax_option_list),
    url(r'^api/paymentoption/', payment_option_list),
    url(r'^api/medicines/', medicine_list),
    url(r'^api/medicine/(?P<pk>[0-9]+)', medicine_detail),
    url(r'^api/storelocations/', store_location_list),
    url(r'^api/medicinecategory/', medicine_category_list),
    url(r'^api/suppliers/', supplier_list),
    url(r'^api/supplier/(?P<pk>[0-9]+)', supplier_detail),
    url(r'^sales/', sale_list),
    url(r'^sale/<int:pk>', sale_detail),
    #fdad urls

    url(r"^medications.ts$", MedicationNamesListAPI.as_view(), name="fdadb-medications.ts-names"),
    url(
        r"^medications.ts/(?P<medication_name>[\w-]+)/strengths$",
        MedicationStrengthsListAPI.as_view(),
        name="fdadb-medications.ts-strengths",
    ),
    url(
        r"^medications.ts/(?P<medication_name>[\w-]+)/strengths/(?P<strength_id>[\d-]+)/ndcs$",
        MedicationNDCsListAPI.as_view(),
        name="fdadb-medications.ts-ndcs",
    ),
    url(r'^api/patientappoints/', get_patient_appointment.as_view()),
    url(r'^api/getpatientmedications/$', PatientMedicationsview.as_view()),
]

usermanagement/urls.py
from django.conf.urls import url
from . import views
from django.views.decorators.csrf import csrf_exempt

from django.views.generic.base import TemplateView
#  1 | Lab_Technician |
# |  2 | Receptionist   |
# |  3 | Nurse          |
# |  4 | Physician      |
# |  5 | Pharmacist     |
# |  7 | Admin


urlpatterns = [
    url(r'^registration/$', views.CreateUserview.as_view(), name='registration'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    #url(r'^logoutedd/$', views.logoutview.as_view(), name='logoussxxst'),
    url(r'^logout/$', views.logoutdoview, name='logout'),
    url(r'^reset/$',views.resetview.as_view(),name='reset'),
    url(r'^resend/$',views.resendpasswordview.as_view(),name='resend'),
    url(r'^resendpassword/(?P<usr>[a-zA-Z0-9]+)/$',views.resendview,name='resendpass'),
    url(r'^resetpassword/$',views.resetpasswordview,name='firstreset'),
    #url(r'^forgot_password/',views.forgotview.as_view(),name= 'forgot'),
    url(r'^forgot/$',views.forgot,name= 'forgotpage'),
    url(r'^(?P<name>[a-z]+)dashboard/$', views.redirectLoginview, name='redirect'),
    #url(r'^createusertype/$', views.createusertypeview.as_view(), name='createusertypes'),
    url(r'^createdoctor/$', views.createdoctorview.as_view(), name='createdoctorview'),
    url(r'^createnurse/$', views.createnurseview.as_view(), name='createnurserview'),
    url(r'^createpharmasist/$', views.createpharasistview.as_view(), name='createpharmasist'),
    url(r'^createlaboratorist/$', views.createlaboratoristview.as_view(), name='createlaboratorist'),
    url(r'^createreceptionist/$', views.createreceptionistview.as_view(), name='createreceptionist'),
    url(r'^createpatient/$', views.createpatientview.as_view(), name='createreceptionist'),
    # url(r'^getcountuser/$', views.createlaboratoristview.as_view(), name='createpharmaview'),
    url(r'^physician_list/$', views.physician_list_view, name='physician'),
    url(r'^physician_list_view/$', views.physician_list_in_receptionist_view, name='physician'),
    url(r'^nurses_list/$', views.Nurses_list_view, name='Nurses'),
    url(r'^laboratorist_list/$', views.Lab_technician_list_view, name='laboratorist'),
    url(r'^pharmacist_list/$', views.Pharmacist_list_view, name='pharmasist'),
    url(r'^receptionist_list/$', views.Receptionist_list_view, name='receptionist'),
    url(r'^patient_list/$', views.patient_list_view, name='receptionist'),
    url(r'^ruduser/(?P<user_id>[0-9]+)/$', views.rudstaffview.as_view(), name='udpatient'),
    url(r'^rudusers_delete/(?P<id>[0-9]+)/$', views.ruduserview.as_view(), name='udpatient'),
    #url(r'^ruddoctor/(?P<pat_id>[a-z A-Z]+-[0-9]+-[0-9]+)/$',views.ruddoctor.as_view(), name='ruddoctor'),
    #url(r'^rud_Patient_for_receptionist_details/(?P<pat_id>[0-9]+)/$', views.Rud_Patient_details_view.as_view(), name='udpatient'),

    # url(r'^rud_doctor_details/(?P<doc_id>[0-9]+)/$', views.Rud_Doctor_details_view.as_view(), name='uddoctor'),
    url(r'^rud_nurse_details/(?P<nurse_user_id>[0-9]+)/$', views.Rud_Nurse_details_view.as_view(), name='udReceptionist'),
    url(r'^rud_Pharmacist_details/(?P<pharma_user_id>[0-9]+)/$', views.Rud_Pharamasist_details_view.as_view(), name='udPharmacist'),
    url(r'^rud_Laboratorist_details/(?P<lab_user_id>[0-9]+)/$', views.Rud_laboratorist_details_view.as_view(), name='udLaboratorist'),
    url(r'^update_Patient_details/(?P<pat_id>[0-9]+)/$', views.Rud_Patient_details_view.as_view(), name='updatepatient'),
    url(r'^rud_doctor_details/(?P<doc_id>[0-9]+)/$', views.Rud_doctor_details_view.as_view(), name='updatedoctor'),

    url(r'^getLabTechnicianList/$', views.get_Lab_Technician_listview.as_view(), name='Lab Technician'),
    url(r'^getReceptionistList/$', views.get_Receptionist_listview.as_view(), name='Receptionist'),
    url(r'^getNurseList/$', views.get_Nurse_listview.as_view(), name='Nurse'),
    url(r'^getdoctor/$', views.get_Physician_listview.as_view(), name='Physician'),
    url(r'^getpharmasist/$', views.get_Pharmacist_listview.as_view(), name='Pharmacist'),
    url(r'^getnurses/$', views.get_Nurse_listview.as_view(), name='Admin'),
    url(r'^getpatients/$', views.get_Patient_listview.as_view(), name='Admin'),
    url(r'getpatientslatest/$',views.get_latestPatient_listview.as_view(), name='latestpateints'),
    url(r'^getpatient/(?P<pat_id>[0-9]+)/$', views.RUDpatientdetailsview.as_view(), name='getpatient'),
    url(r'^rudpatientdetails/(?P<pat_id>[0-9]+)/$', views.RUDpatientdetailsview.as_view(), name='udpatientdetails'),
    url(r'^patient__profile/(?P<pat_id>[0-9]+)/$', views.patientpartview, name='createreceptionist'),
    
    url(r'^doctor_profile/(?P<doc_id>[0-9]+)/$', views.doctor_profile_view, name='doctorProfile'),
    url(r'^get_Physician_Profile/(?P<doc_id>[0-9]+)/$', views.get_Physician_Profile.as_view(), name='doctorProfile'),

    url(r'^nurse_profile/(?P<nurse_user_id>[0-9]+)/$', views.nurse_profile_view, name='nurseProfile'),
    url(r'^get_nurse_profile/(?P<nurse_user_id>[0-9]+)/$', views.get_nurse_profile.as_view(), name='nurseProfile'),

    url(r'^pharma_profile/(?P<pharma_user_id>[0-9]+)/$', views.pharma_profile_view, name='pharmaProfile'),
    url(r'^get_pharma_profile/(?P<pharma_user_id>[0-9]+)/$', views.get_pharma_profile.as_view(), name='pharmaProfile'),

    url(r'^laboratorist_profile/(?P<lab_user_id>[0-9]+)/$', views.laboratorist_profile_view, name='laboratoristProfile'),
    url(r'^get_laboratorist_profile/(?P<lab_user_id>[0-9]+)/$', views.get_laboratorist_profile.as_view(), name='laboratoristProfile'),

    url(r'^receptionist_profile/(?P<id>[0-9]+)/$', views.receptionist_profile_view, name='receptionistProfile'),
    url(r'^get_receptionist_profile/(?P<user_id>[0-9]+)/$', views.get_receptionist_profile.as_view(), name='receptionistProfile'),

    url(r'^healthrecordview/(?P<pat_id>[0-9]+)/$', views.healthrecordview, name='createreceptionist'),
    url(r'^patients/$', views.patient_listehr_physian_view, name='createphysianehr'),
    url(r'^patient_profile/(?P<pat_id>[0-9]+)/$', views.patientpartphysicanview, name='patientphysican'),
    url(r'^health_record/(?P<pat_id>[0-9]+)/$', views.healthrecordphysicanview, name='healthrecordphsican'),
    url(r'^nursehealthrecord/$', views.patient_listehr_nurse_view, name='createnurseehr'),
    url(r'^patient-profile/(?P<pat_id>[0-9]+)/$', views.patientpartnurseview, name='patientnurse'),
    url(r'^health-record/(?P<pat_id>[0-9]+)/$', views.healthrecordnurseview, name='healthrecordnurse'),
    url(r'^summary/(?P<pat_id>[0-9]+)/$', views.OPdrecordview, name='createreceptionist'),
    # url(r'^patientphoto/(?P<id>[0-9]+)/$', views.FileView.as_view(),
    #     name='creatpatientphoto'),
    url(r'^userlogin/$', views.userloginview, name='userlogin'),
    url(r'^$', views.userloginview, name='userlogin'),
    url(r'^lab_test_details/(?P<pat_id>[a-z A-Z]+-[0-9]+-[0-9]+)/$', views.lab_test_details, name='laboratory_test_details'),
    url(r'^patientListInLaboratorist/(?P<pat_id>[0-9]+)/$', views.patientlaboratoristview, name='patientlaboratory'),
    url(r'^patients_list_view_laboratorist/$', views.patientListViewInLaboratorist, name='patientListViewInLaboratorist'),
    url(r'^patient_laboratory_test_details/$', views.patientLaboratoryTestDetailsView, name='patient_laboratory_test_details'),
    url(r'^patient_profile_details/(?P<pat_id>[0-9]+)/$', views.patientpartlaboratoristview, name='patientpartlaboratorist'),

    # url(r'^usersignup/$', views.usersignupview, name='usersignup'),
    url(r'^trouble-signin/$', views.trouble, name='trouble'),
    # # url(r'^resetpasswordsettings/(?P<pk>[0-9]+)//$', views.resetpasswordsettings, name='reset'),
    # url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.reset, name='reset'),
    # url(r'^$', views.index, name='index'),
    # url(r'^changepassword/$', views.ChangePasswordview.as_view(), name='changepassword'),
    # url(r'^changepasswordtemplete/$', views.changepasswordtemplate, name='changepasswordtemplate'),
    # url(r'^ruduser/(?P<id>[0-9]+)/$', views.RUDemplyeeview.as_view(), name='createallergy'),
    # url(r'^rudpersonaldetails/$', views.RUDemplyeedetailsview.as_view(), name='rudpersonaldetails'),
    # url(r'^createpatient/$', views.Createpatientview.as_view(), name='createpatient'),
    # url(r'^creatpatientdetails/$', views.Creatpatientdetailsview.as_view(), name='creatpatientdetails'),
    # url(r'^createpatientprofile/$', views.Createpatientprofileview.as_view(), name='createpatientprofile'),
    # url(r'^createpatientalternatecontact/$', views.Creatpatientalternatecontactview.as_view(),
    #     name='creatpatientalternatecontact'),
    #
    url(r'^getpatientsdoctor/$', views.get_patient_doctor.as_view(), name='getpatient'),
    url(r'^getappointedpatients/$', views.appointedpatients.as_view(), name='getpatient'),

    # url(r'^getpatientdetails/(?P<patient_id>[0-9]+)/$', views.Getpatientdetailsview.as_view(),
    #     name='getpatientdetails'),
    # url(r'^getpatientprofile/(?P<patient_id>[0-9]+)/$', views.Getpatientprofileview.as_view(),
    #     name='getpatientprofile'),
    # url(r'^getpatientalternatecontact/(?P<patient_id>[0-9]+)/$', views.Getpatientalternatecontactview.as_view(),
    #     name='getpatientalternate'),
    #
    # url(r'^rudpatient/(?P<id>[0-9]+)/$', views.Rudpatientview.as_view(), name='udpatient'),
    # url(r'^rudpatientdetails/(?P<id>[0-9]+)/$', views.RUDpatientdetailsview.as_view(), name='udpatientdetails'),
    # url(r'^rudpatientprofile/(?P<id>[0-9]+)/$', views.Rudpatientprofileview.as_view(), name='udpatientprofile'),
    # url(r'^rudpatientalternatecontact/(?P<id>[0-9]+)/$', views.RUDpatientalternatecontactview.as_view(),
    #     name='udpatientalternatecontact'),
    # url(r'^patients/(?P<orgnastion_id>[0-9]+)/$', views.Patieantlistview.as_view(), name='patientlist'),
    #

appointments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from usermanagement.models import Doctors, Patient

class DoctorSlots(models.Model):
    doctor = models.ForeignKey(Doctors,on_delete=models.CASCADE)
    starttime = models.TimeField(null=True,blank=True)
    endtime = models.TimeField(null=True,blank=True)
    consultationfee = models.IntegerField(null=True)
    breakslots = models.TextField(null=True,blank=True)
    appointmnetduration = models.CharField(null=True,blank=True,max_length=100)

class Appointment(models.Model):
    type= [
        (1,"in-patient"),
        (2,"out-patient")
    ]
    state =[
        (0,"closed"),
        (1,"active"),
        (2,"not applicable")
    ]
    patient = models.ForeignKey(Patient,on_delete=models.SET_NULL, null=True,blank=True, related_name="appointments")
    doctor = models.ForeignKey(Doctors,on_delete=models.CASCADE)
    appointmentType = models.PositiveSmallIntegerField(choices=type,default=2)
    flag = models.PositiveSmallIntegerField(choices=state,default=2)
    bookingdate = models.DateField(null=True)
    bookingtime = models.TimeField(null=True)

    def __str__(self):
        return str(self.id)

class BlockSlots(models.Model):
    doctor = models.ForeignKey(Doctors,on_delete=models.CASCADE)
    blockdate = models.DateField(null=True)
    blockslot = models.TimeField(null=True)# -*- coding: utf-8 -*-

templates/Password_change_Success.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/login-signup.css'%}">
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

</head>
<style>
 #head-nav {
    box-shadow: 0px 0px 2px 2px #efefef;
    margin: 15px;
}
.head-logo{
    color: #017b8b;
    font-weight: 500;
    font-size: 30px;
}
.nav-link{
    color: rgba(117, 115, 115, 0.85);
    font-size: 17px;
}

</style>
<body>
<br><br><br>
<div class="container">

    <div class="login-form">
        <div class="main-div">
            <div class="panel">
                <h2 style="color:#017b8b;font-weight:bold;font-size:25px;">Reset Password</h2>

            </div>
            <div class="form-group">
                <h3>You have Successfully changed your password</h3>
            </div>
            <div class="form-group">
                <a href='{% url "usemanagement:userlogin" %}'>
                    <button type="button" class="btn">Continue</button>
                </a>
            </div>

        </div>

    </div>
</div>

<script>
        window.drf = {
          csrfHeaderName: "X-CSRFTOKEN",
          csrfCookieName: "csrftoken"
        };

</script>

<script src="{% static 'js/csrf.js' %}"></script>
<script src="{% static 'js/apicals.js' %}"></script>
</body>
</html>

templates/autosearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
</head>
<body>
<form id="searchform" method="get" role="search">
    <input id="searchfield" />
    <input type="submit" name="go" value="go!" />
</form>
<script>
$("#searchfield").click(function(){
var arr = [];
$.getJSON("coptcodes.json", function(data) {
    $.each(data, function(key, value) {
        if ($.inArray(value.name, arr) === -1) {
            arr.push(value.name)
        }
    })
    console.log(arr)
});
}
);
</script>
</body>

</html>

templates/ehr_patient_list_in_physician_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/extend_settings.html
{% load staticfiles %}

{% block head %}
 {% include 'navbar.html' %}
{% endblock %}

{% block body %}
    {% include 'settings.html' %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/extend_userprofile.html
{% load staticfiles %}

{% block head %}
 {% include 'navbar.html' %}
{% endblock %}

{% block body %}
    {% include 'userprofile.html' %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/forgotpassword_link.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/login-signup.css'%}">
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

</head>
<style>
 #head-nav {
    box-shadow: 0px 0px 2px 2px #efefef;
    margin: 15px;
}
.head-logo{
    color: #017b8b;
    font-weight: 500;
    font-size: 30px;
}
.nav-link{
    color: rgba(117, 115, 115, 0.85);
    font-size: 17px;
}

</style>
<body>
<br><br><br>
<div class="container">

    <div class="login-form">
        <div class="main-div">
            <div class="panel">
                <h2 style="color:#017b8b;font-weight:bold;font-size:25px;">Reset Password</h2>

            </div>
            <div class="form-group">
                <h3>Click on the link sent to your Email to Reset your password</h3>
            </div>
            <div class="form-group">
                <a href='{% url "usemanagement:userlogin" %}'>
                    <button type="button" class="btn">Continue</button>
                </a>
            </div>
        </div>

    </div>
</div>

<script>
        window.drf = {
          csrfHeaderName: "X-CSRFTOKEN",
          csrfCookieName: "csrftoken"
        };

</script>

<script src="{% static 'js/csrf.js' %}"></script>
<script src="{% static 'js/apicals.js' %}"></script>
</body>
</html>